//! The wrapper script DZL hooks into Steam's launch options for DayZ.
//!
//! Steam launches the game, not us: when the client is already running,
//! `steam -applaunch` hands the request over IPC and the game inherits that
//! client's environment. A wrapper therefore has to arrive through Steam's own
//! `%command%`. DZL points that at this script once and then owns the script,
//! so changing a setting never touches Steam's config again.

use crate::commands::config::{DisplayMode, WrapperConfig};

/// Splits a free-form argument string, honouring single and double quotes so
/// `--filter 'nearest thing'` stays one argument.
pub(crate) fn split_args(value: &str) -> Vec<String> {
    let mut args = Vec::new();
    let mut current = String::new();
    let mut quote: Option<char> = None;
    let mut started = false;

    for c in value.chars() {
        match quote {
            Some(q) if c == q => quote = None,
            Some(_) => current.push(c),
            None if c == '\'' || c == '"' => {
                quote = Some(c);
                started = true;
            }
            None if c.is_whitespace() => {
                if started || !current.is_empty() {
                    args.push(std::mem::take(&mut current));
                    started = false;
                }
            }
            None => current.push(c),
        }
    }
    if started || !current.is_empty() {
        args.push(current);
    }
    args
}

/// Wraps a value in single quotes so the shell treats it literally.
pub(crate) fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

/// Quotes only what needs it, so a generated script stays readable.
fn maybe_quote(value: &str) -> String {
    let safe = !value.is_empty()
        && value
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || "_.:/=+-".contains(c));
    if safe {
        value.to_string()
    } else {
        shell_quote(value)
    }
}

pub(crate) fn valid_env_name(name: &str) -> bool {
    !name.is_empty()
        && name
            .chars()
            .enumerate()
            .all(|(i, c)| c == '_' || c.is_ascii_alphabetic() || (i > 0 && c.is_ascii_digit()))
}

pub(crate) fn gamescope_args(wrapper: &WrapperConfig) -> Vec<String> {
    let mut args: Vec<String> = Vec::new();
    if let Some(width) = wrapper.width {
        args.push("-W".into());
        args.push(width.to_string());
    }
    if let Some(height) = wrapper.height {
        args.push("-H".into());
        args.push(height.to_string());
    }
    if let Some(refresh) = wrapper.refresh {
        args.push("-r".into());
        args.push(refresh.to_string());
    }
    match wrapper.display_mode {
        DisplayMode::Fullscreen => args.push("-f".into()),
        DisplayMode::Borderless => args.push("-b".into()),
        DisplayMode::Windowed => {}
    }
    if wrapper.force_grab_cursor {
        args.push("--force-grab-cursor".into());
    }
    args.extend(split_args(&wrapper.extra_args));
    args
}

/// The command as a Steam user would write it, for the settings preview.
pub(crate) fn preview_line(wrapper: &WrapperConfig) -> String {
    let mut parts: Vec<String> = Vec::new();
    if wrapper.gamemode {
        parts.push("gamemoderun".into());
    }
    if wrapper.gamescope {
        parts.push("gamescope".into());
        parts.extend(gamescope_args(wrapper));
        parts.push("--".into());
    }
    parts.push("%command%".into());
    parts.join(" ")
}

/// The script DZL writes and Steam runs. Each wrapper is guarded by a lookup,
/// so a binary that is not installed can never stop the game from starting or
/// silently take the other wrapper down with it.
pub(crate) fn wrapper_script(wrapper: &WrapperConfig) -> String {
    let mut out = String::from("#!/bin/sh\n");
    out.push_str("# Generated by DZL. Do not edit; change the launcher's settings instead.\n");

    for entry in &wrapper.env {
        let Some((name, value)) = entry.split_once('=') else {
            continue;
        };
        if !valid_env_name(name) {
            continue;
        }
        out.push_str(&format!("export {}={}\n", name, shell_quote(value)));
    }

    let scoped: Vec<String> = gamescope_args(wrapper).iter().map(|a| maybe_quote(a)).collect();
    let scoped = if scoped.is_empty() {
        String::new()
    } else {
        format!(" {}", scoped.join(" "))
    };

    out.push_str("have() { command -v \"$1\" >/dev/null 2>&1; }\n");
    match (wrapper.gamemode, wrapper.gamescope) {
        (true, true) => out.push_str(&format!(
            "if have gamemoderun && have gamescope; then\n  \
             exec gamemoderun gamescope{scoped} -- \"$@\"\n\
             elif have gamescope; then\n  \
             exec gamescope{scoped} -- \"$@\"\n\
             elif have gamemoderun; then\n  \
             exec gamemoderun \"$@\"\nfi\n",
        )),
        (false, true) => out.push_str(&format!(
            "if have gamescope; then\n  exec gamescope{scoped} -- \"$@\"\nfi\n",
        )),
        (true, false) => {
            out.push_str("if have gamemoderun; then\n  exec gamemoderun \"$@\"\nfi\n")
        }
        (false, false) => {}
    }
    out.push_str("exec \"$@\"\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::config::{DisplayMode, WrapperConfig};

    fn full() -> WrapperConfig {
        WrapperConfig {
            gamemode: true,
            gamescope: true,
            width: Some(2560),
            height: Some(1440),
            refresh: Some(180),
            display_mode: DisplayMode::Fullscreen,
            force_grab_cursor: true,
            extra_args: "--hdr-enabled".into(),
            env: vec!["LD_PRELOAD=".into()],
            previous_launch_options: None,
        }
    }

    #[test]
    fn gamescope_args_follow_the_settings() {
        assert_eq!(
            gamescope_args(&full()),
            vec![
                "-W",
                "2560",
                "-H",
                "1440",
                "-r",
                "180",
                "-f",
                "--force-grab-cursor",
                "--hdr-enabled"
            ]
        );
    }

    #[test]
    fn borderless_and_windowed_pick_the_right_flag() {
        let mut wrapper = full();
        wrapper.display_mode = DisplayMode::Borderless;
        assert!(gamescope_args(&wrapper).contains(&"-b".to_string()));
        assert!(!gamescope_args(&wrapper).contains(&"-f".to_string()));

        wrapper.display_mode = DisplayMode::Windowed;
        let args = gamescope_args(&wrapper);
        assert!(!args.contains(&"-b".to_string()) && !args.contains(&"-f".to_string()));
    }

    #[test]
    fn script_runs_both_wrappers_and_exports_the_environment() {
        let script = wrapper_script(&full());
        assert!(script.starts_with("#!/bin/sh\n"));
        assert!(script.contains("export LD_PRELOAD=''"));
        assert!(script.contains(
            "exec gamemoderun gamescope -W 2560 -H 1440 -r 180 -f --force-grab-cursor --hdr-enabled -- \"$@\""
        ));
        assert!(
            script.contains("exec gamescope"),
            "gamescope alone when GameMode is missing"
        );
        assert!(
            script.contains("exec gamemoderun \"$@\""),
            "GameMode alone when gamescope is missing"
        );
        assert!(
            script.trim_end().ends_with("exec \"$@\""),
            "always falls through to the game"
        );
    }

    #[test]
    fn script_with_everything_off_just_runs_the_game() {
        let script = wrapper_script(&WrapperConfig::default());
        assert!(!script.contains("gamescope"));
        assert!(!script.contains("gamemoderun"));
        assert!(script.trim_end().ends_with("exec \"$@\""));
    }

    #[test]
    fn script_quotes_values_and_rejects_bad_variable_names() {
        let wrapper = WrapperConfig {
            gamescope: true,
            extra_args: "--filter 'nearest thing'".into(),
            env: vec![
                "PROTON_LOG=1".into(),
                "WITH SPACE=value".into(),
                "SHELL_OUT=$(id)".into(),
            ],
            ..WrapperConfig::default()
        };
        let script = wrapper_script(&wrapper);

        assert!(script.contains("export PROTON_LOG='1'"));
        assert!(!script.contains("WITH SPACE"), "invalid names are dropped");
        assert!(
            script.contains("export SHELL_OUT='$(id)'"),
            "values are never expanded"
        );
        assert!(
            script.contains("'nearest thing'"),
            "quoted extra args stay one argument"
        );
    }

    /// Every shape of the generated script has to be valid shell, so it is fed
    /// to `sh -n` rather than trusted by eye.
    #[test]
    fn every_script_shape_parses_as_shell() {
        let shapes = [
            WrapperConfig::default(),
            full(),
            WrapperConfig {
                gamemode: true,
                ..WrapperConfig::default()
            },
            WrapperConfig {
                gamescope: true,
                extra_args: "--filter 'nearest thing' --hdr-enabled".into(),
                env: vec!["ODD='quote".into()],
                ..WrapperConfig::default()
            },
        ];

        for (i, wrapper) in shapes.iter().enumerate() {
            let path = std::env::temp_dir().join(format!("dzl-script-shape-{}.sh", i));
            std::fs::write(&path, wrapper_script(wrapper)).unwrap();
            let status = std::process::Command::new("sh")
                .arg("-n")
                .arg(&path)
                .status()
                .unwrap();
            assert!(status.success(), "shape {} is not valid shell", i);
            let _ = std::fs::remove_file(&path);
        }
    }

    #[test]
    fn shell_quote_handles_embedded_quotes() {
        assert_eq!(shell_quote("it's"), "'it'\\''s'");
    }

    #[test]
    fn preview_reads_like_a_steam_launch_option() {
        assert_eq!(
            preview_line(&full()),
            "gamemoderun gamescope -W 2560 -H 1440 -r 180 -f --force-grab-cursor --hdr-enabled -- %command%"
        );
        assert_eq!(preview_line(&WrapperConfig::default()), "%command%");
    }
}
