//! The wrapper script DZL hooks into Steam's launch options for DayZ.
//!
//! Steam launches the game, not us: when the client is already running,
//! `steam -applaunch` hands the request over IPC and the game inherits that
//! client's environment. A wrapper therefore has to arrive through Steam's own
//! `%command%`. DZL points that at this script once and then owns the script,
//! so changing a setting never touches Steam's config again.

use crate::commands::config::{AppConfig, DisplayMode, WrapperConfig};
use crate::commands::system::{
    binary_exists, detect_steam_path, steam_root, steam_running, DAYZ_APP_ID,
};
use crate::steam_vdf::{find_local_config, read_launch_options, write_launch_options, LocalConfig};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use tauri::Manager;

const SCRIPT_NAME: &str = "dzl-wrap.sh";

/// Splits a free-form argument string, honouring single and double quotes so
/// `--filter 'nearest thing'` stays one argument.
pub(crate) fn split_args(value: &str) -> Vec<String> {
    let mut args = Vec::new();
    let mut current = String::new();
    let mut quote: Option<char> = None;
    let mut started = false;

    for c in value.chars() {
        match quote {
            Some(q) if c == q => quote = None,
            Some(_) => current.push(c),
            None if c == '\'' || c == '"' => {
                quote = Some(c);
                started = true;
            }
            None if c.is_whitespace() => {
                if started || !current.is_empty() {
                    args.push(std::mem::take(&mut current));
                    started = false;
                }
            }
            None => current.push(c),
        }
    }
    if started || !current.is_empty() {
        args.push(current);
    }
    args
}

/// Wraps a value in single quotes so the shell treats it literally.
pub(crate) fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

/// Quotes only what needs it, so a generated script stays readable.
fn maybe_quote(value: &str) -> String {
    let safe = !value.is_empty()
        && value
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || "_.:/=+-".contains(c));
    if safe {
        value.to_string()
    } else {
        shell_quote(value)
    }
}

pub(crate) fn valid_env_name(name: &str) -> bool {
    !name.is_empty()
        && name
            .chars()
            .enumerate()
            .all(|(i, c)| c == '_' || c.is_ascii_alphabetic() || (i > 0 && c.is_ascii_digit()))
}

pub(crate) fn gamescope_args(wrapper: &WrapperConfig) -> Vec<String> {
    let mut args: Vec<String> = Vec::new();
    if let Some(width) = wrapper.width {
        args.push("-W".into());
        args.push(width.to_string());
    }
    if let Some(height) = wrapper.height {
        args.push("-H".into());
        args.push(height.to_string());
    }
    if let Some(refresh) = wrapper.refresh {
        args.push("-r".into());
        args.push(refresh.to_string());
    }
    match wrapper.display_mode {
        DisplayMode::Fullscreen => args.push("-f".into()),
        DisplayMode::Borderless => args.push("-b".into()),
        DisplayMode::Windowed => {}
    }
    if wrapper.force_grab_cursor {
        args.push("--force-grab-cursor".into());
    }
    args.extend(split_args(&wrapper.extra_args));
    args
}

/// The command as a Steam user would write it, for the settings preview.
pub(crate) fn preview_line(wrapper: &WrapperConfig) -> String {
    let mut parts: Vec<String> = Vec::new();
    if wrapper.gamemode {
        parts.push("gamemoderun".into());
    }
    if wrapper.gamescope {
        parts.push("gamescope".into());
        parts.extend(gamescope_args(wrapper));
        parts.push("--".into());
    }
    parts.push("%command%".into());
    parts.join(" ")
}

/// The script DZL writes and Steam runs. Each wrapper is guarded by a lookup,
/// so a binary that is not installed can never stop the game from starting or
/// silently take the other wrapper down with it.
pub(crate) fn wrapper_script(wrapper: &WrapperConfig) -> String {
    let mut out = String::from("#!/bin/sh\n");
    out.push_str("# Generated by DZL. Do not edit; change the launcher's settings instead.\n");

    for entry in &wrapper.env {
        let Some((name, value)) = entry.split_once('=') else {
            continue;
        };
        if !valid_env_name(name) {
            continue;
        }
        out.push_str(&format!("export {}={}\n", name, shell_quote(value)));
    }

    let scoped: Vec<String> = gamescope_args(wrapper).iter().map(|a| maybe_quote(a)).collect();
    let scoped = if scoped.is_empty() {
        String::new()
    } else {
        format!(" {}", scoped.join(" "))
    };

    out.push_str("have() { command -v \"$1\" >/dev/null 2>&1; }\n");
    match (wrapper.gamemode, wrapper.gamescope) {
        (true, true) => out.push_str(&format!(
            "if have gamemoderun && have gamescope; then\n  \
             exec gamemoderun gamescope{scoped} -- \"$@\"\n\
             elif have gamescope; then\n  \
             exec gamescope{scoped} -- \"$@\"\n\
             elif have gamemoderun; then\n  \
             exec gamemoderun \"$@\"\nfi\n",
        )),
        (false, true) => out.push_str(&format!(
            "if have gamescope; then\n  exec gamescope{scoped} -- \"$@\"\nfi\n",
        )),
        (true, false) => {
            out.push_str("if have gamemoderun; then\n  exec gamemoderun \"$@\"\nfi\n")
        }
        (false, false) => {}
    }
    out.push_str("exec \"$@\"\n");
    out
}

/// What DZL made of the launch options Steam already held.
#[derive(Debug)]
pub enum ImportResult {
    Empty,
    AlreadyHooked,
    Parsed {
        wrapper: WrapperConfig,
        trailing_args: Vec<String>,
    },
    /// The original value, for the user to accept losing or to keep.
    Unparseable(String),
}

/// Sequences that mean the value is doing something we will not try to model.
const SHELL_METACHARS: &[&str] = &["&&", "||", ";", "|", "$(", "`", ">", "<"];

fn is_wrapper_binary(token: &str, name: &str) -> bool {
    token == name || token.ends_with(&format!("/{}", name))
}

/// Reads launch options already set in Steam into wrapper settings.
///
/// The grammar is deliberately narrow: leading `VAR=value` assignments, then an
/// optional `gamemoderun`, then an optional `gamescope <flags> --`, then
/// `%command%`, then any trailing game arguments. Anything else is refused
/// rather than guessed at, because guessing here silently changes how somebody's
/// game starts.
pub fn import_launch_options(value: &str, script_path: &str) -> ImportResult {
    let trimmed = value.trim();
    if trimmed.is_empty() {
        return ImportResult::Empty;
    }
    if trimmed.starts_with(script_path) {
        return ImportResult::AlreadyHooked;
    }
    if SHELL_METACHARS.iter().any(|m| trimmed.contains(m)) {
        return ImportResult::Unparseable(trimmed.to_string());
    }

    let tokens = split_args(trimmed);
    let mut wrapper = WrapperConfig::default();
    let mut index = 0;

    while let Some(token) = tokens.get(index) {
        let Some((name, val)) = token.split_once('=') else {
            break;
        };
        if !valid_env_name(name) {
            break;
        }
        wrapper.env.push(format!("{}={}", name, val));
        index += 1;
    }

    if tokens
        .get(index)
        .is_some_and(|t| is_wrapper_binary(t, "gamemoderun"))
    {
        wrapper.gamemode = true;
        index += 1;
    }

    if tokens
        .get(index)
        .is_some_and(|t| is_wrapper_binary(t, "gamescope"))
    {
        wrapper.gamescope = true;
        index += 1;

        let mut extra: Vec<String> = Vec::new();
        let mut closed = false;
        let mut mode_seen = false;

        while let Some(token) = tokens.get(index) {
            index += 1;
            match token.as_str() {
                "--" => {
                    closed = true;
                    break;
                }
                "-f" | "--fullscreen" => {
                    wrapper.display_mode = DisplayMode::Fullscreen;
                    mode_seen = true;
                }
                "-b" | "--borderless" => {
                    wrapper.display_mode = DisplayMode::Borderless;
                    mode_seen = true;
                }
                "--force-grab-cursor" => wrapper.force_grab_cursor = true,
                "-W" | "--output-width" | "-H" | "--output-height" | "-r"
                | "--nested-refresh" => {
                    let Some(number) = tokens.get(index).and_then(|n| n.parse::<u32>().ok()) else {
                        return ImportResult::Unparseable(trimmed.to_string());
                    };
                    index += 1;
                    match token.as_str() {
                        "-W" | "--output-width" => wrapper.width = Some(number),
                        "-H" | "--output-height" => wrapper.height = Some(number),
                        _ => wrapper.refresh = Some(number),
                    }
                }
                other if other.starts_with('-') => extra.push(other.to_string()),
                // A bare word before `--` is another wrapper we cannot model.
                _ => return ImportResult::Unparseable(trimmed.to_string()),
            }
        }

        if !closed {
            return ImportResult::Unparseable(trimmed.to_string());
        }
        if !mode_seen {
            // Neither -f nor -b means gamescope opens an ordinary window.
            wrapper.display_mode = DisplayMode::Windowed;
        }
        wrapper.extra_args = extra.join(" ");
    }

    if tokens.get(index).map(String::as_str) != Some("%command%") {
        return ImportResult::Unparseable(trimmed.to_string());
    }
    index += 1;

    ImportResult::Parsed {
        wrapper,
        trailing_args: tokens[index..].to_vec(),
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum HookState {
    NotInstalled,
    Installed,
    /// Steam holds something else, so it was changed outside DZL.
    Changed,
    /// Steam's config could not be read at all.
    Unreadable,
}

/// Everything the Wrappers section needs to describe itself.
#[derive(Debug, Serialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct WrapperStatus {
    pub hook: HookState,
    /// What Steam currently holds for DayZ, escapes already resolved.
    pub launch_options: Option<String>,
    pub script_path: String,
    pub expected_hook: String,
    pub preview: String,
    /// Steam account whose config holds the hook.
    pub account_id: Option<String>,
    pub steam_running: bool,
    pub gamescope_installed: bool,
    pub gamescope_version: Option<String>,
    pub gamemode_installed: bool,
}

pub(crate) fn hook_state(current: Option<&str>, expected: &str) -> HookState {
    match current.map(str::trim) {
        None | Some("") => HookState::NotInstalled,
        Some(value) if value == expected => HookState::Installed,
        Some(_) => HookState::Changed,
    }
}

/// Whether the wrapper settings can actually take effect. Nothing enabled needs
/// no hook, so an untouched install never warns about one.
pub(crate) fn hook_satisfied(wrapper: &WrapperConfig, state: HookState) -> bool {
    if !wrapper.gamemode && !wrapper.gamescope {
        return true;
    }
    state == HookState::Installed
}

pub(crate) fn script_path(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|e| format!("no-data-dir: {}", e))?;
    Ok(dir.join(SCRIPT_NAME))
}

fn expected_hook(path: &Path) -> String {
    format!("{} %command%", path.display())
}

/// Writes the script for the current settings and makes it executable.
pub(crate) fn write_script(app: &tauri::AppHandle, config: &AppConfig) -> Result<PathBuf, String> {
    let path = script_path(app)?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("script-failed: {}", e))?;
    }
    std::fs::write(&path, wrapper_script(&config.wrapper))
        .map_err(|e| format!("script-failed: {}: {}", path.display(), e))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))
            .map_err(|e| format!("script-failed: {}", e))?;
    }

    Ok(path)
}

fn local_config(config: &AppConfig) -> Result<LocalConfig, String> {
    let steam_path = config
        .steam_path
        .clone()
        .filter(|p| Path::new(p).is_dir())
        .or_else(detect_steam_path)
        .ok_or_else(|| "no-steam-path: could not find your Steam library".to_string())?;
    find_local_config(&steam_root(&steam_path))
}

/// What Steam holds for DayZ right now. `Ok(None)` means the file was readable
/// and simply had no value.
pub(crate) fn current_launch_options(config: &AppConfig) -> Result<Option<String>, String> {
    let found = local_config(config)?;
    let text = std::fs::read_to_string(&found.path)
        .map_err(|e| format!("read-failed: {}: {}", found.path.display(), e))?;
    Ok(read_launch_options(&text, DAYZ_APP_ID))
}

/// True when Steam's launch options point at our script. Used by the join
/// preflight, so it never fails: an unreadable config just means not hooked.
pub(crate) fn hook_installed(app: &tauri::AppHandle, config: &AppConfig) -> bool {
    let Ok(path) = script_path(app) else {
        return false;
    };
    let current = current_launch_options(config).ok().flatten();
    hook_state(current.as_deref(), &expected_hook(&path)) == HookState::Installed
}

fn gamescope_version() -> Option<String> {
    let output = crate::commands::system::external_command("gamescope")
        .arg("--version")
        .output()
        .ok()?;
    let text = String::from_utf8_lossy(&output.stdout).to_string()
        + &String::from_utf8_lossy(&output.stderr);
    // "gamescope version 3.16.25 (gcc 16.1.1)"
    text.split_whitespace()
        .skip_while(|w| *w != "version")
        .nth(1)
        .map(|v| v.to_string())
}

fn status(app: &tauri::AppHandle, config: &AppConfig) -> WrapperStatus {
    let path = script_path(app).unwrap_or_else(|_| PathBuf::from(SCRIPT_NAME));
    let expected = expected_hook(&path);

    let (hook, launch_options, account_id) = match local_config(config) {
        Ok(found) => match std::fs::read_to_string(&found.path) {
            Ok(text) => {
                let current = read_launch_options(&text, DAYZ_APP_ID);
                (
                    hook_state(current.as_deref(), &expected),
                    current,
                    Some(found.account_id),
                )
            }
            Err(_) => (HookState::Unreadable, None, Some(found.account_id)),
        },
        Err(_) => (HookState::Unreadable, None, None),
    };

    let gamescope_installed = binary_exists("gamescope");
    WrapperStatus {
        hook,
        launch_options,
        script_path: path.display().to_string(),
        expected_hook: expected,
        preview: preview_line(&config.wrapper),
        account_id,
        steam_running: steam_running(),
        gamescope_installed,
        gamescope_version: gamescope_installed.then(gamescope_version).flatten(),
        gamemode_installed: binary_exists("gamemoderun"),
    }
}

#[tauri::command]
pub fn get_wrapper_status(app: tauri::AppHandle) -> WrapperStatus {
    let config = crate::commands::config::read_config(&app);
    status(&app, &config)
}

/// Points Steam's launch options at our script, importing whatever was there.
///
/// Steam holds `localconfig.vdf` in memory and writes it back when it exits, so
/// the client has to be down for the edit to survive. `replace` is the user's
/// answer to launch options DZL could not parse.
#[tauri::command]
pub async fn install_wrapper_hook(
    app: tauri::AppHandle,
    replace: bool,
) -> Result<WrapperStatus, String> {
    let mut config = crate::commands::config::read_config(&app);
    let found = local_config(&config)?;
    let path = script_path(&app)?;
    let expected = expected_hook(&path);

    let text = std::fs::read_to_string(&found.path)
        .map_err(|e| format!("read-failed: {}: {}", found.path.display(), e))?;
    let current = read_launch_options(&text, DAYZ_APP_ID);

    match import_launch_options(
        current.as_deref().unwrap_or_default(),
        &path.display().to_string(),
    ) {
        ImportResult::Empty | ImportResult::AlreadyHooked => {}
        ImportResult::Parsed {
            wrapper,
            trailing_args,
        } => {
            config.wrapper = WrapperConfig {
                previous_launch_options: current.clone(),
                ..wrapper
            };
            for arg in trailing_args {
                if !config.custom_args.contains(&arg) {
                    config.custom_args.push(arg);
                }
            }
        }
        ImportResult::Unparseable(original) => {
            if !replace {
                return Err(format!("import-conflict: {}", original));
            }
            config.wrapper.previous_launch_options = current.clone();
        }
    }

    write_script(&app, &config)?;

    // Steam has to be down for the write to survive, and back up afterwards so
    // the user can launch. A failed write is reported after Steam is restored.
    let restart = steam_running();
    if restart {
        crate::commands::system::shutdown_steam().await?;
    }
    let write = write_launch_options(&found, DAYZ_APP_ID, &expected);
    if restart {
        crate::commands::system::start_steam().await?;
    }
    write?;

    crate::commands::config::save_config(&app, &config)?;
    Ok(status(&app, &config))
}

/// Puts back whatever Steam held before DZL hooked it, and deletes the script.
#[tauri::command]
pub async fn remove_wrapper_hook(app: tauri::AppHandle) -> Result<WrapperStatus, String> {
    let mut config = crate::commands::config::read_config(&app);
    let found = local_config(&config)?;
    let restore = config
        .wrapper
        .previous_launch_options
        .clone()
        .unwrap_or_default();

    let restart = steam_running();
    if restart {
        crate::commands::system::shutdown_steam().await?;
    }
    let write = write_launch_options(&found, DAYZ_APP_ID, &restore);
    if restart {
        crate::commands::system::start_steam().await?;
    }
    write?;

    if let Ok(path) = script_path(&app) {
        let _ = std::fs::remove_file(path);
    }
    config.wrapper.previous_launch_options = None;
    crate::commands::config::save_config(&app, &config)?;
    Ok(status(&app, &config))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::config::{DisplayMode, WrapperConfig};

    fn full() -> WrapperConfig {
        WrapperConfig {
            gamemode: true,
            gamescope: true,
            width: Some(2560),
            height: Some(1440),
            refresh: Some(180),
            display_mode: DisplayMode::Fullscreen,
            force_grab_cursor: true,
            extra_args: "--hdr-enabled".into(),
            env: vec!["LD_PRELOAD=".into()],
            previous_launch_options: None,
        }
    }

    #[test]
    fn gamescope_args_follow_the_settings() {
        assert_eq!(
            gamescope_args(&full()),
            vec![
                "-W",
                "2560",
                "-H",
                "1440",
                "-r",
                "180",
                "-f",
                "--force-grab-cursor",
                "--hdr-enabled"
            ]
        );
    }

    #[test]
    fn borderless_and_windowed_pick_the_right_flag() {
        let mut wrapper = full();
        wrapper.display_mode = DisplayMode::Borderless;
        assert!(gamescope_args(&wrapper).contains(&"-b".to_string()));
        assert!(!gamescope_args(&wrapper).contains(&"-f".to_string()));

        wrapper.display_mode = DisplayMode::Windowed;
        let args = gamescope_args(&wrapper);
        assert!(!args.contains(&"-b".to_string()) && !args.contains(&"-f".to_string()));
    }

    #[test]
    fn script_runs_both_wrappers_and_exports_the_environment() {
        let script = wrapper_script(&full());
        assert!(script.starts_with("#!/bin/sh\n"));
        assert!(script.contains("export LD_PRELOAD=''"));
        assert!(script.contains(
            "exec gamemoderun gamescope -W 2560 -H 1440 -r 180 -f --force-grab-cursor --hdr-enabled -- \"$@\""
        ));
        assert!(
            script.contains("exec gamescope"),
            "gamescope alone when GameMode is missing"
        );
        assert!(
            script.contains("exec gamemoderun \"$@\""),
            "GameMode alone when gamescope is missing"
        );
        assert!(
            script.trim_end().ends_with("exec \"$@\""),
            "always falls through to the game"
        );
    }

    #[test]
    fn script_with_everything_off_just_runs_the_game() {
        let script = wrapper_script(&WrapperConfig::default());
        assert!(!script.contains("gamescope"));
        assert!(!script.contains("gamemoderun"));
        assert!(script.trim_end().ends_with("exec \"$@\""));
    }

    #[test]
    fn script_quotes_values_and_rejects_bad_variable_names() {
        let wrapper = WrapperConfig {
            gamescope: true,
            extra_args: "--filter 'nearest thing'".into(),
            env: vec![
                "PROTON_LOG=1".into(),
                "WITH SPACE=value".into(),
                "SHELL_OUT=$(id)".into(),
            ],
            ..WrapperConfig::default()
        };
        let script = wrapper_script(&wrapper);

        assert!(script.contains("export PROTON_LOG='1'"));
        assert!(!script.contains("WITH SPACE"), "invalid names are dropped");
        assert!(
            script.contains("export SHELL_OUT='$(id)'"),
            "values are never expanded"
        );
        assert!(
            script.contains("'nearest thing'"),
            "quoted extra args stay one argument"
        );
    }

    /// Every shape of the generated script has to be valid shell, so it is fed
    /// to `sh -n` rather than trusted by eye.
    #[test]
    fn every_script_shape_parses_as_shell() {
        let shapes = [
            WrapperConfig::default(),
            full(),
            WrapperConfig {
                gamemode: true,
                ..WrapperConfig::default()
            },
            WrapperConfig {
                gamescope: true,
                extra_args: "--filter 'nearest thing' --hdr-enabled".into(),
                env: vec!["ODD='quote".into()],
                ..WrapperConfig::default()
            },
        ];

        for (i, wrapper) in shapes.iter().enumerate() {
            let path = std::env::temp_dir().join(format!("dzl-script-shape-{}.sh", i));
            std::fs::write(&path, wrapper_script(wrapper)).unwrap();
            let status = std::process::Command::new("sh")
                .arg("-n")
                .arg(&path)
                .status()
                .unwrap();
            assert!(status.success(), "shape {} is not valid shell", i);
            let _ = std::fs::remove_file(&path);
        }
    }

    #[test]
    fn shell_quote_handles_embedded_quotes() {
        assert_eq!(shell_quote("it's"), "'it'\\''s'");
    }

    #[test]
    fn hook_state_compares_against_the_expected_line() {
        let expected = "/home/u/.local/share/com.dzl.launcher/dzl-wrap.sh %command%";
        assert_eq!(hook_state(None, expected), HookState::NotInstalled);
        assert_eq!(hook_state(Some(""), expected), HookState::NotInstalled);
        assert_eq!(hook_state(Some(expected), expected), HookState::Installed);
        assert_eq!(
            hook_state(Some("gamescope -f -- %command%"), expected),
            HookState::Changed
        );
    }

    #[test]
    fn the_hook_is_only_needed_when_a_wrapper_is_enabled() {
        assert!(hook_satisfied(
            &WrapperConfig::default(),
            HookState::NotInstalled
        ));

        let on = WrapperConfig {
            gamescope: true,
            ..WrapperConfig::default()
        };
        assert!(!hook_satisfied(&on, HookState::NotInstalled));
        assert!(!hook_satisfied(&on, HookState::Changed));
        assert!(hook_satisfied(&on, HookState::Installed));
    }

    #[test]
    fn imports_the_real_world_string() {
        let result = import_launch_options(
            "LD_PRELOAD=\"\" gamemoderun gamescope -W 2560 -H 1440 -f -r 180 --force-grab-cursor -- %command%",
            "/tmp/dzl-wrap.sh",
        );
        let ImportResult::Parsed {
            wrapper,
            trailing_args,
        } = result
        else {
            panic!("expected a parse, got {:?}", result);
        };

        assert!(wrapper.gamemode);
        assert!(wrapper.gamescope);
        assert_eq!(wrapper.width, Some(2560));
        assert_eq!(wrapper.height, Some(1440));
        assert_eq!(wrapper.refresh, Some(180));
        assert_eq!(wrapper.display_mode, DisplayMode::Fullscreen);
        assert!(wrapper.force_grab_cursor);
        assert_eq!(wrapper.env, vec!["LD_PRELOAD=".to_string()]);
        assert_eq!(wrapper.extra_args, "");
        assert!(trailing_args.is_empty());
    }

    #[test]
    fn imports_gamescope_alone_and_keeps_unknown_flags() {
        let result = import_launch_options("gamescope -b --hdr-enabled -- %command%", "/tmp/w.sh");
        let ImportResult::Parsed { wrapper, .. } = result else {
            panic!("expected a parse")
        };

        assert!(!wrapper.gamemode);
        assert_eq!(wrapper.display_mode, DisplayMode::Borderless);
        assert_eq!(wrapper.extra_args, "--hdr-enabled");
    }

    #[test]
    fn imports_long_form_gamescope_flags() {
        let result = import_launch_options(
            "gamescope --output-width 3440 --output-height 1440 --nested-refresh 144 --fullscreen -- %command%",
            "/tmp/w.sh",
        );
        let ImportResult::Parsed { wrapper, .. } = result else {
            panic!("expected a parse")
        };

        assert_eq!(wrapper.width, Some(3440));
        assert_eq!(wrapper.height, Some(1440));
        assert_eq!(wrapper.refresh, Some(144));
        assert_eq!(wrapper.display_mode, DisplayMode::Fullscreen);
    }

    #[test]
    fn gamescope_without_a_mode_flag_imports_as_windowed() {
        let result = import_launch_options("gamescope -W 1920 -- %command%", "/tmp/w.sh");
        let ImportResult::Parsed { wrapper, .. } = result else {
            panic!("expected a parse")
        };
        assert_eq!(wrapper.display_mode, DisplayMode::Windowed);
    }

    #[test]
    fn imports_gamemode_alone() {
        let result = import_launch_options("gamemoderun %command%", "/tmp/w.sh");
        let ImportResult::Parsed { wrapper, .. } = result else {
            panic!("expected a parse")
        };
        assert!(wrapper.gamemode);
        assert!(!wrapper.gamescope);
    }

    #[test]
    fn trailing_arguments_are_kept_separately() {
        let result = import_launch_options("gamemoderun %command% -noSplash", "/tmp/w.sh");
        let ImportResult::Parsed { trailing_args, .. } = result else {
            panic!("expected a parse")
        };
        assert_eq!(trailing_args, vec!["-noSplash".to_string()]);
    }

    #[test]
    fn an_empty_value_imports_nothing() {
        assert!(matches!(
            import_launch_options("   ", "/tmp/w.sh"),
            ImportResult::Empty
        ));
    }

    #[test]
    fn our_own_hook_is_recognised() {
        assert!(matches!(
            import_launch_options("/tmp/w.sh %command%", "/tmp/w.sh"),
            ImportResult::AlreadyHooked
        ));
    }

    #[test]
    fn anything_outside_the_grammar_is_refused() {
        for value in [
            "mangohud %command%",
            "sh -c 'gamescope -- %command%'",
            "gamemoderun %command% && echo done",
            "gamescope -f %command%",
            "gamescope -f -- steam-run %command%",
            "gamemoderun /usr/bin/something %command%",
            "gamemoderun gamescope -f --",
            "gamescope -W wide -- %command%",
        ] {
            assert!(
                matches!(
                    import_launch_options(value, "/tmp/w.sh"),
                    ImportResult::Unparseable(_)
                ),
                "should refuse: {}",
                value
            );
        }
    }

    #[test]
    fn preview_reads_like_a_steam_launch_option() {
        assert_eq!(
            preview_line(&full()),
            "gamemoderun gamescope -W 2560 -H 1440 -r 180 -f --force-grab-cursor --hdr-enabled -- %command%"
        );
        assert_eq!(preview_line(&WrapperConfig::default()), "%command%");
    }
}
